title: Jacob Dix
url: http://libraryofdix.com
description: 'Personal site of Jacob Dix - Machine Learning Engineer in London, England'
keywords:
 - Jacob Dix


author:
    name: Jacob Dix
    email: jacob@dix.org.uk
    github: https://github.com/libraryofdix/
    linkedin: http://www.linkedin.com/in/jdix/
    leetcode: https://leetcode.com/JakeeDix/
    
sections:
 - projects
 - about
 - journal 
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /assets/themes/default/js/site.min.js?131513?131513
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git
